### ISSUE TITLE
Dendrogram style trees

### ISSUE THREAD

**Issue by dan-knight** [uclahs-cds/package-CancerEvolutionVisualization#114]
Allow users to create dendrograms rather than radial trees. This should allow plotting larger trees, with many more nodes.

- [x] #115
- [x] #116
- [x] #117

**Comment by dan-knight** [comment]
In dendrogram mode, the `length` of each branch should correspond to the "vertical" length of the branch.

**Comment by dan-knight** [comment]
Which visual style is preferred? Is one or the other strictly correct? From some brief research with @whelena, option A seems to be more prevalent in the field. It would also be simpler to implement.

## Option A
<img width="415" alt="Screenshot 2024-01-05 at 2 56 13 PM" src="https://github.com/uclahs-cds/package-CancerEvolutionVisualization/assets/56950335/bc9b0b79-c327-4a7b-a7e8-2469a71832a0">

## Option B
<img width="488" alt="Screenshot 2024-01-05 at 2 56 02 PM" src="https://github.com/uclahs-cds/package-CancerEvolutionVisualization/assets/56950335/c2336687-13f9-468d-b35b-b077abdee57b">

**Comment by whelena** [comment]
> Which visual style is preferred? Is one or the other strictly correct? From some brief research with @whelena, option A seems to be more prevalent in the field. It would also be simpler to implement.

I think option A follows common interpretation of a dendrogram where intersections = common ancestor and option B implies that the children share some common mutations after they supposedly diverged from the parent

> In dendrogram mode, the `length` of each branch should correspond to the "vertical" length of the branch.
