### ISSUE TITLE
Error in get.root.node(tree.df) : More than one root node detected.  

### ISSUE THREAD

**Issue by maotian06** [uclahs-cds/package-CancerEvolutionVisualization#130]
Sorry to bother you both @dan-knight @whelena !

I was trying to plot one emulsiphy result and got this error. I was wondering if this is an edge case with multiple root nodes, or it is something common so I need to pre-process the data?

### Error Message:
```
Error in get.root.node(tree.df) : More than one root node detected.  
```

### Source Code:
```
phylogeny.df <- fread(
    file = input.phylogeny.file,
    header = TRUE,
    sep = '\t',
    na.strings = c('NA', '.', ''),
    fill = TRUE
    );

CEV.dt <- convert.CEV(phylogeny.df);
plt <- SRCGrob(
    CEV.dt,
    main = paste(patient, 'Tree'),
    horizontal.padding = 3,
    scale1 = 2,
    add.normal = TRUE
    );
```                                                                                                          
Path for `input.phylogeny.file` is:
```
/hot/project/disease/HeadNeckTumor/ATHC-000072-WholeGenomeLandscape/metapipeline-v5.0.0/output/call-SRC-1.1.0/emulsiphy//NTATGEFL000185/NTATGEFL000185_phylogeny.tsv
```

**Comment by whelena** [comment]
Your input file has rows where the parent is NA, which means emulsiphy failed to find a parent for those samples. You can remove them prior to running `convert.CEV` since CEV assigns children with no parent to normal (root node)
